name: Issue Template

on:
  issues:
    types:
      - opened
      - closed

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the issue is closed
        if: github.event_name == 'issues' && github.event.action == 'closed'
        run: |
          SLUG=$(echo "${{ github.event.issue.title }}" | tr -cd '[:alnum:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
          FILE_CONTENT=$(echo "${{ github.event.issue.body }}")
          
          FILE_PATH="src/app/users/${SLUG}.js"
          
          echo "// Content for the user ${SLUG}" > "${FILE_PATH}"
          echo "${FILE_CONTENT}" >> "${FILE_PATH}"
          
          echo "File ${FILE_PATH} created successfully."
          
    env:
      BODY: ${{ github.event.issue.body }}
