name: Create File on Issue Close

on:
  issues:
    types:
      - closed

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "kudlu2004@gmail.com"
          git config user.name "Kartikeya Saini"

      - name: Check if the issue is closed
        run: |
          SLUG=$(echo "${{ github.event.issue.title }}" | tr -cd '[:alnum:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
          FILE_PATH="src/app/users/${SLUG}.js"

          # Check if the file already exists for the issue
          if [ ! -f "${FILE_PATH}" ]; then
            ISSUE_BODY="${{ github.event.issue.body }}"
            ESCAPED_BODY=$(echo "$ISSUE_BODY" | sed ':a;N;$!ba;s/\n/\\n/g')
            
            # Append issue body content to the file
            echo -e "const data = {\n  issueBody: \"$ESCAPED_BODY\"\n};\n\nexport default data;\n" > "${FILE_PATH}"

            # Add and commit the new file
            git add "${FILE_PATH}"
            git commit -m "Add file for issue: $SLUG"
            git push
          else
            echo "File ${FILE_PATH} already exists. Skipping."
          fi
