name: Issue Template

on:
  issues:
    types:
      - opened
      - closed

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the issue is closed
        if: github.event_name == 'issues' && github.event.action == 'closed'
        run: |
          # Extract information from the issue body
          SLUG=$(echo "$BODY" | jq -r .details.slug)
          
          # Create file.js in @/app/users directory
          touch "src/app/users/file.js"
          
    env:
      BODY: ${{ github.event.issue.body }}
